server:
  port: 9090

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6542/stats}
    username: ${SPRING_DATASOURCE_USERNAME:stats}
    password: ${SPRING_DATASOURCE_PASSWORD:stats}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"