services:
  main-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${MAIN_DB_NAME:-main_service}
      POSTGRES_USER: ${MAIN_DB_USER:-app}
      POSTGRES_PASSWORD: ${MAIN_DB_PASSWORD:-devpass123}
    ports:
      - "5432:5432"
    volumes:
      - main_pgdata:/var/lib/postgresql/data

  stats-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${STATS_DB_NAME:-stats_service}
      POSTGRES_USER: ${STATS_DB_USER:-app}
      POSTGRES_PASSWORD: ${STATS_DB_PASSWORD:-devpass123}
    ports:
      - "5433:5432"
    volumes:
      - stats_pgdata:/var/lib/postgresql/data

  stats-server:
    build:
      context: ./ewm-stats-service/stats-server
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/${STATS_DB_NAME:-stats_service}
      SPRING_DATASOURCE_USERNAME: ${STATS_DB_USER:-app}
      SPRING_DATASOURCE_PASSWORD: ${STATS_DB_PASSWORD:-devpass123}
      SERVER_PORT: 9090
      SPRING_APPLICATION_NAME: stats-server
    ports:
      - "9090:9090"

  main-service:
    build:
      context: ./ewm-main-service
    depends_on:
      - main-db
      - stats-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-db:5432/${MAIN_DB_NAME:-main_service}
      SPRING_DATASOURCE_USERNAME: ${MAIN_DB_USER:-app}
      SPRING_DATASOURCE_PASSWORD: ${MAIN_DB_PASSWORD:-devpass123}
      SERVER_PORT: 8080
      SPRING_APPLICATION_NAME: main-service
      STATS_SERVER_URL: http://stats-server:9090
    ports:
      - "8080:8080"

volumes:
  main_pgdata:
  stats_pgdata:
