services:
  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    ports:
      - "6542:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U stats -d stats" ]
      interval: 5s
      timeout: 3s
      retries: 20

  stats-server:
    build:
      context: ./ewm-stats-service/stats-server
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats
      SERVER_PORT: 9090
      SPRING_APPLICATION_NAME: stats-server
    ports:
      - "9090:9090"

  main-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: main_service
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
    ports:
      - "6543:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U main -d main_service" ]
      interval: 5s
      timeout: 3s
      retries: 20

  main-service:
    build:
      context: ./ewm-main-service
    depends_on:
      stats-server:
        condition: service_started
      main-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-db:5432/main_service
      SPRING_DATASOURCE_USERNAME: main
      SPRING_DATASOURCE_PASSWORD: main
      SERVER_PORT: 8080
      SPRING_APPLICATION_NAME: main-service
      STATS_SERVER_URL: http://stats-server:9090
    ports:
      - "8080:8080"
