server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6542/ewm}
    username: ${SPRING_DATASOURCE_USERNAME:ewm}
    password: ${SPRING_DATASOURCE_PASSWORD:ewm}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

stats:
  server:
    url: ${STATS_BASE_URL:http://stats-server:9090}
  client:
    base-url: ${stats.server.url}
    app-name: ${STATS_APP_NAME:ewm-main-service}
    connect-timeout-ms: ${STATS_CONNECT_TIMEOUT_MS:3000}
    read-timeout-ms: ${STATS_READ_TIMEOUT_MS:3000}
