server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:6544/ewm_main
    username: ewm
    password: ewm
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

stats:
  client:
    base-url: ${STATS_BASE_URL:http://stats-server:9090}
    app-name: ${STATS_APP_NAME:ewm-main-service}
    connect-timeout-ms: 3000
    read-timeout-ms: 3000
